apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: reverse-words-git
spec:
  type: git
  params:
  - name: url
    value: <reversewords_git_repo>
  - name: revision
    value: main
  - name: sslVerify
    value: "false"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: reverse-words-image
spec:
  type: image
  params:
  - name: url
    value: <reversewords_quay_repo>
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: reverse-words-build-pipeline
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  params:
  - name: imageTag
    type: string
    default: latest
    description: Tag for the built image
  tasks:

  - name: lint
    taskRef:
      name: golangci-lint
    params:
      - name: package
        value: <golang_package>
      - name: flags
        value: --verbose
      - name: GOOS
        value: "linux"
    resources:
      inputs:
      - name: source
        resource: app-git

  - name: test
    taskRef:
      name: golang-test
    runAfter:
      - lint
    params:
      - name: package
        value: <golang_package>
      - name: GOOS
        value: "linux"
    resources:
      inputs:
      - name: source
        resource: app-git

  - name: build-and-push
    taskRef:
      name: build-from-dockerfile
    runAfter:
      - test
    params:
      - name: DOCKERFILE_PATH
        value: "./Dockerfile"
      - name: IMAGE_TAG
        value: "$(params.imageTag)"
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image

  - name: update-stage-deployment-image
    taskRef:
      name: image-updater
    runAfter:
      - build-and-push
    params:
      - name: driver
        value: "github"
      - name: file-path
        value: "deployment.yaml"
      - name: image-repo
        value: "<reversewords_quay_repo>"
      - name: new-image-url
        value: "<reversewords_quay_repo>:$(params.imageTag)"
      - name: source-branch
        value: "stage"
      - name: source-repo
        value: "<imageBuilder_sourcerepo>"
      - name: update-key
        value: "spec.template.spec.containers.0.image"
      - name: insecure
        value: "true"
      - name: branch-generate-name
        value: ""
  finally:
    - name: notify-test-failure
      when:
        - input: $(tasks.test.status)
          operator: in
          values: ["Failed"]
      taskRef:
        name: send-to-slack-channel
