apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Production release
        - $patch: replace
        image: quay.io/sysadmin-dev/tekton-reversewords:68cfaf1ccd8aed9ad0ae94f10027870a95a56919
        name: reverse-words
