apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Production release
        - $patch: replace
        image: quay.io/pamelamatun/tekton-reversewords:9963caf2aa7571cea5ac5794820e30e56cf0120b
        name: reverse-words
