apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Production release
        - $patch: replace
        image: quay.io/pamelamatun/tekton-reversewords:637082c98edaff2e3433157aa57dc6a7b53b6921
        name: reverse-words
